### ISSUE TITLE
generating input csvs from sequencing data

### ISSUE THREAD

**Issue by jackieduckie** [itmoon7/onconpc#5]
Hi there,

I'm interested in your work and hopefully you could help answer a few questions: 

1. Do you think OncoNPC with the trained model is applicable on WGS or other panel cancer sequencing data provided that the targeted gene regions are all covered?  
2. If so, would you be able to provide documentation on generating input files for onconpc from bams? Specifically, what SNV/CNV callers are preferred, and whether there are scripts available to generate input csvs from vcfs? 

I noticed that there is a closed issue from Sep 2023 requesting input generation code but the link to the pre-processing script ([link](https://github.com/itmoon7/onconpc/blob/main/codes/process_features_profile_genie_v2.py)) is no longer valid.

Thank you.

**Comment by itmoon7** [comment]
Thank you for reaching out!

1. Yes, OncoNPC can be used with Whole Genome Sequencing (WGS) or cancer panel sequencing data, provided there's a match with the set of target genes. For detailed information on these targeted genes, please refer to the following link: [OncoNPC input features](https://github.com/itmoon7/onconpc/blob/main/Supplementary%20Materials/onconpc_features.csv).

2. Direct access to BAM files is not available within our framework. Nonetheless, we offer scripts that enable the generation of OncoNPC input features directly from raw panel sequencing data from [cBioPortal](https://www.cbioportal.org). An example notebook demonstrating this process can be found here: [OncoNPC Prediction from cBioPortal Raw Data](https://github.com/itmoon7/onconpc/blob/main/onconpc_prediction_and_explanation_for_cup_tumors_from_cbio_raw.ipynb). You can access all the necessary source codes in our repository.

Due to a change in the filename, the original link might no longer work. For the pre-processing code, please use this link: [OncoNPC Pre-processing Code](https://github.com/itmoon7/onconpc/blob/main/codes/process_features.py).

Please let us know if you have any further questions or comments!
